global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:8000']
  - job_name: 'web'
    static_configs:
      - targets: ['web:8000']
  - job_name: 'mt5-rest'
    static_configs:
      - targets: ['mt5-rest:8080'] 