services:
  - type: web
    name: bitcoin-scalper-dashboard
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: cd /app && streamlit run src/dashboard/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEMO_MODE
        value: "false"
      - key: STREAMLIT_SERVER_PORT
        value: "8080"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: MT5_LOGIN
        value: "101490774"
      - key: MT5_PASSWORD
        value: "MatLB356&"
      - key: MT5_SERVER
        value: "AvaTrade-Live"

  - type: worker
    name: bitcoin-scalper-bot
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: cd /app && python run_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MT5_LOGIN
        value: "101490774"
      - key: MT5_PASSWORD
        value: "MatLB356&"
      - key: MT5_SERVER
        value: "Ava-Demo 1-MT5" 