apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-web
  template:
    metadata:
      labels:
        app: btc-web
    spec:
      containers:
        - name: btc-web
          image: <REGISTRY>/btc-web:latest # Ã€ builder/pusher par CI
          ports:
            - containerPort: 8000
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: btc-web
spec:
  selector:
    app: btc-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort 