mt5_login: "oALmrjleifKNl5erlvd3mVOnmVI7a1jc+omnDAA4A8c="
mt5_password: "Rn7c9rrY5cQ6rZmgnej2VCZAf1HdLLpfAW4+FeLr1rA="
mt5_server: "Ava-Demo 1-MT5"
mt5_path: "/Applications/MetaTrader 5.app/Contents/MacOS/MetaTrader 5" 